### ISSUE TITLE
unknown error QAQ

### ISSUE THREAD

**Issue by Volt-F** [Geralt-TYH/obsidian-zhihu-crawler#3]
Exception in Tkinter callback

Traceback (most recent call last):

  File "C:\Users\86151\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)

  File "E:\Desktop\obsidian-zhihu-crawler-1.1\gui.py", line 52, in clip
    urls, titles = get_article_urls_in_collection(collection_id)

  File "E:\Desktop\obsidian-zhihu-crawler-1.1\main.py", line 119, in get_article_urls_in_collection
    while offset < article_nums:

TypeError: '<' not supported between instances of 'int' and 'NoneType'

**Comment by cabudon** [comment]
这个报错意味着在你的程序中出现了一个类型错误。具体来说，代码中的两个实例（一个整数和一个NoneType）之间不能使用小于号（‘<’）进行比较。

根据报错信息，问题出现在main.py文件的第119行，即get_article_urls_in_collection函数中的while循环内部的比较操作。其中，offset是一个整数，而article_nums则为NoneType。

要解决这个问题，你需要检查article_nums的值是否被正确地初始化或赋予一个整数值。确保在比较操作之前，所有参与比较的变量都具有有效的值。如果article_nums应该是一个数字，但却为NoneType，则需要找到导致它没有被正确赋值的原因，并修复它。

你可以在main.py文件的第119行附近检查相关的代码，确保article_nums变量被正确地初始化，并且在使用之前具有有效的整数值。

如果你需要更具体的帮助，请提供更多相关代码段，我将尽力提供更准确的建议。
